
SHELL := /bin/bash

help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . -type f -name "eval.log" -ls -delete
	find . -type f -name "train.log" -ls -delete
	find . | grep -E ".pytype" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	find . | grep -E "__MACOSX" | xargs rm -rf
	find data -type f -name "*.tar" -ls -delete
	find data -type f -name "*.tar.gz" -ls -delete
	find data -type f -name "*.tgz" -ls -delete
	find data -type f -name "*.zip" -ls -delete
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	pre-commit run -a

install: ## Install dependencies
	if [ ! -d .venv ]; then python -m venv .venv; fi

	source .venv/bin/activate && \
		pip install --upgrade pip && \
		pip install flit && \
		flit install -s --only-deps --env && \
	deactivate;

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

test: ## Run not slow tests
	pytest -k "not slow" -k "not train"

test-full: ## Run all tests
	pytest -k "not train"
