# list of loggers to disable
disable_loggers:
  - faiss.loader

# disable python warnings if they annoy you
ignore_warnings: False

# ask user for tags if none are provided in the config
enforce_tags: True

# monkey-patch tensor classes to have pretty representations
lovely_tensors: True

# define precision of matrix multiplication with tensor cores
matmul_precision: medium

# pretty print config tree at the start of the run using Rich library
print_config: True
