# @package _global_

defaults:
  - _self_
  - data: caltech101
  - model: null
  - callbacks:
      - rich_progress_bar
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: baseline/clip

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is often necessary for evaluation
ckpt_path: null
